with burn in, sharding, and reports

diff --git a/.github/workflows/e2e-test.yml b/.github/workflows/e2e-test.yml
--- a/.github/workflows/e2e-test.yml
+++ b/.github/workflows/e2e-test.yml
@@ -10,10 +10,41 @@ concurrency:
 
 env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  TEST_ENV: dev
+  TEST_COMMAND: npm run test:pw
+  INSTALL_COMMAND: npm ci
 
 jobs:
+  vars:
+    runs-on: kubernetes-default
+    outputs:
+      test_env: ${{ env.TEST_ENV }}
+      test_command: ${{ env.TEST_COMMAND }}
+      install_command: ${{ env.INSTALL_COMMAND }}
+    steps:
+      - run: echo "Exposing env vars"
+
+  burn-in:
+    needs: vars
+    uses: ./.github/workflows/rwf-burn-in.yml
+    with:
+      base-ref: 'main'
+      test-directory: 'playwright/'
+      test-pattern: '.*\.spec\.ts'
+      repeat-count: 3 # this will run 6 times between the 2 browsers (chrome & chromium)
+      retry-count: 0
+      install-command: ${{ needs.vars.outputs.install_command }}
+      test-command: ${{ needs.vars.outputs.test_command }}
+
   e2e-test:
+    needs: [vars, burn-in]
     timeout-minutes: 10
+    if: needs.burn-in.outputs.runE2E == 'true'
+    strategy:
+      fail-fast: false
+      matrix:
+        shardIndex: [1, 2]
+        shardTotal: [2]
     runs-on: kubernetes-default
     steps:
       - uses: actions/checkout@v4
@@ -33,7 +64,7 @@ jobs:
             playwright-${{ runner.os }}-
 
       - name: Install dependencies
-        run: npm ci
+        run: ${{ needs.vars.outputs.install_command }}
 
       - name: Install Playwright Chromium and Google Chrome
         run: |
@@ -41,13 +72,43 @@ jobs:
           npx playwright install chrome
 
       - name: Run Playwright tests
-        run: npm run test:pw
+        run: ${{ needs.vars.outputs.test_command }} --shard ${matrix.shardIndex}/${matrix.shardTotal}
 
-      - uses: actions/upload-artifact@v4
-        if: ${{ !cancelled() }}
+      - name: Copy trace files to blob-report
+        run: |
+          mkdir -p blob-report/trace
+          cp -r test-results/**/*.zip blob-report/trace || true
+
+      - name: Upload shared blob report
+        uses: actions/upload-artifact@v4
+        if: always()
         with:
-          name: playwright-artifacts
-          path: |
-            playwright-report/
-            test-results/
+          name: blob-report-${{ matrix.shardIndex }}
+          path: blob-report
+          retention-days: 3
+
+  merge-reports:
+    needs: e2e-test
+    # even if the previous jobs in the needs: list failed, still run this job
+    if: always() && needs.burn-in.outputs.runE2E == 'true'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download shard reports
+        uses: actions/download-artifact@v4
+        with:
+          path: all-blob-reports
+          pattern: blob-report-*
+          merge-multiple: true
+
+      - name: Merge Playwright reports
+        run: |
+          mkdir -p playwright-report/trace
+          cp -r all-blob-reports/*/trace/* playwright-report/trace || true
+          npx playwright merge-reports --reporter=html all-blob-reports
+
+      - name: Upload merged report
+        uses: actions/upload-artifact@v4
+        with:
+          name: playwright-report
+          path: playwright-report
           retention-days: 3
